// <auto-generated />
namespace WebApplication8.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class smns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(smns));
        
        string IMigrationMetadata.Id
        {
            get { return "202010031001533_smns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
