// <auto-generated />
namespace WebApplication8.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class dfhjksw1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dfhjksw1));
        
        string IMigrationMetadata.Id
        {
            get { return "202009191035477_dfhjksw1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
