// <auto-generated />
namespace WebApplication8.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class lead_NatureOfBusinessId_Optional : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lead_NatureOfBusinessId_Optional));
        
        string IMigrationMetadata.Id
        {
            get { return "202105120914448_lead_NatureOfBusinessId_Optional"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
