// <auto-generated />
namespace WebApplication8.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Invoicetable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Invoicetable));
        
        string IMigrationMetadata.Id
        {
            get { return "202103221243224_Invoice-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
